validation/validation/config/routes.rb
Rails.application.routes.draw do
  resources :manage_user
  root to:'manage_user#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

validation/validation/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

validation/validation/app/models/user.rb
class Validator < ActiveModel::Validator
   def validate(record)
     if record.birthdate==nil || record.birthdate >= Date.today
         record.errors.add :birthdate, "invalid birthdate"
       end
    end
end

class User < ApplicationRecord
    validates :firstname,:lastname, presence: true
    validates_with Validator
    validates :gender,presence: {message:'You must select gender'}
    validates :address,length: {maximum:15,message:'Maximum %{count} characters allowed'}
    validates :username, presence: true
    validates :username, uniqueness: true
    validates :password, presence: true
    validates :password, confirmation: { case_sensitive: true }
    validates :phoneno,:alternatephoneno, format: { with: /[0-9]\d*|0\d+/,message: "Invalid Phone No" }
    validates :email, format: { with: /[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+/,message: "Invalid Email Id" }
    #validates :terms_and_condition, acceptance: {message:'T&C must be accepted'}
    #validates :title, confirmation: true
    
    #validates :discription, exclusion: { in: %w(www us ca jp),message: "%{value} is reserved." }
    #validates :title, format: { with: /\A[a-zA-Z]+\z/,message: "only allows letters" }
    #validates :title, inclusion: { in: %w(small medium large),message: "%{value} is not a valid size" }
    
    
end

validation/validation/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

validation/validation/app/controllers/manage_user_controller.rb
class ManageUserController < ApplicationController
    def index
    end
    
    def new
        @info=User.new
    end
    
    def create
        @info = User.new(user_params)
        @info.save 
        if @info.save
            render 'index' 
        else
            render 'new'
        end 
    end
    
    private
    def user_params  
    params.require(:user).permit(:firstname,:middlename,:lastname,:birthdate,:city,:state,:country,:address,:gender,:companyname,:position,:email,:phoneno,:alternatephoneno,:username,:password,:password_confirmation)
    end
end

validation/validation/app/helpers/application_helper.rb
module ApplicationHelper
end

validation/validation/app/helpers/manage_user_helper.rb
module ManageUserHelper
end

validation/validation/app/views/layouts/application.html.erb
<!--<!DOCTYPE html>
<html>
  <head>
    <title>Validation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
-->
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Validation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= yield %>
  </body>
</html>

validation/validation/app/views/manage_user/index.html.erb
<h2>Your response has been saved successfully</h2><br>
<%= link_to 'Send another response', new_manage_user_path %>

validation/validation/app/views/manage_user/new.html.erb
<%= form_for @info, url:manage_user_index_path,method:'post' do |f| %>
<div class="container form-group mt-5">
    <h2>Personal information</h2><hr><br><br>
    <div class="row">
            <div class='col'>First Name<%=f.text_field :firstname, class:'form-control'%><b class="text-danger"><%=@info.errors[:firstname].to_sentence%></b><br><br></div>
            <div class='col'>Middle Name<%=f.text_field :middlename, class:'form-control'%><br><br></div>
            <div class='col'>Last Name<%=f.text_field :lastname, class:'form-control'%><b class="text-danger"><%=@info.errors[:lastname].to_sentence%></b><br><br></div>
    </div>

    <div class='row'>
    <div class='col-4'>Birth Date<%=f.date_field :birthdate, class:'form-control'%><b class="text-danger"><%=@info.errors[:birthdate].to_sentence%></b><br><br></div>
    <div class='col-6'>Gender<br><div class='col-4 '><%=f.radio_button :gender,'Male',class:'mr-3'%><label>Male</div> <div class='col-4'><%=f.radio_button :gender,'Female',class:'mr-3'%>Female</div><b class="text-danger"><%=@info.errors[:gender].to_sentence%></b><br><br></div>
    </div>

    <div class='row'>
        <div class='col'>City<%=f.text_field :city,class:'form-control'%><br><br></div>
        <div class='col'>State<%=f.text_field :state,class:'form-control'%><br><br></div>
        <div class='col'>Contry<%=f.text_field :country,class:'form-control'%><br><br></div>
    </div>

    <div class='row'>
        <div class='col-8'>Address<%=f.text_area :address,class:'form-control'%><b class="text-danger"><%=@info.errors[:address].to_sentence%></b><br><br><br><br></div>
    </div>

    <h2>Professional information</h2><hr><br><br>
    <div class='row'>
        <div class='col'>Company Name<%=f.text_field :companyname, class:'form-control'%><br><br></div>
        <div class='col'>Position<%=f.text_field :position,class:'form-control'%><br><br></div>
    </div>

    <div class='row'>
        <div class='col-8'>Email<%=f.text_field :email,class:'form-control'%><b class="text-danger"><%=@info.errors[:email].to_sentence%></b><br><br></div>
    </div>

    <div class='row'>
        <div class='col'>Phone No<%=f.text_field :phoneno,class:'form-control'%><b class="text-danger"><%=@info.errors[:phoneno].to_sentence%></b><br><br></div>
        <div class='col'>Alternate Phone No<%=f.text_field :alternatephoneno,class:'form-control'%><b class="text-danger"><%=@info.errors[:alternatephoneno].to_sentence%></b><br><br></div>
    </div>

    <div class='row'>
        <div class='col-8'>Username<%=f.text_field :username,class:'form-control'%><b class="text-danger"><%=@info.errors[:username].to_sentence%></b><br><br></div>
    </div>

    <div class='row'>
        <div class='col'>password<%=f.text_field :password, class:'form-control'%><b class="text-danger"><%=@info.errors[:password_confirmation].to_sentence%> <%=@info.errors[:password].to_sentence%></b><br><br></div>
        <div class='col'>Confirm password<%=f.text_field :password_confirmation,class:'form-control'%><b class="text-danger"><%=@info.errors[:password_confirmation].to_sentence%><%=@info.errors[:password].to_sentence%></b><br><br></div>
    </div>

    <div class='row mb-5'>
        <div class='col-4'><%=f.submit "Submit",class:"btn btn-success"%></div>
    </div>
</div>
<%end%>